myword = "mustafatahran"
print(myword.capitalize())
print(myword.count("C"))
print(myword.find("r"))
print(myword.index("h"))
print(myword.isalnum())
print(myword.isalpha())
print(myword.isdecimal())
print(myword.isdigit())
print(myword.isidentifier())
print(myword.islower())
print(myword.isnumeric())
print(myword.isprintable())
print(myword.isspace())
print(myword.istitle())
print(myword.isupper())
print(myword.lower())
print(myword.lstrip("f"))
print(myword.rstrip("p"))
print(myword.replace("u", "o"))
print(myword.split("t"))
print(myword.swapcase())
print(myword.title())
print(myword.upper())